### ISSUE TITLE
GUI设计

### ISSUE THREAD

**Issue by WendyZheng9953** [sebuaa2020/Team101#10]
我对建图之后是否还保存robot存在疑问。
由于是仿真环境，建图成功后是否可以直接kill现在的robot?然后在导航模块重新spawn一个。这样做的好处是，代码比较简单。而且即使是在实际环境中，需求文档中提到建图后机器人应该**回到初始位置**。
请大家做一下决定!

**Comment by insunday** [comment]
实现来讲这样的确是一个比较好的办法, 但是如果从实际模拟的角度, 现实中不会一个机器人建图,另一个机器人导航呢,

**Comment by WendyZheng9953** [comment]
需求文档和设计文档中应该都指明的是只使用一个机器人。

**Comment by pampamda** [comment]
我认为重新spawn一个robot是个不错的办法，或许可以试试这个较为简单的方案，看看实际运行效果如何

**Comment by WendyZheng9953** [comment]
最终解决方案是重新spawn
