### ISSUE TITLE
gazebo不稳定

### ISSUE THREAD

**Issue by WendyZheng9953** [sebuaa2020/Team101#11]
有可能遇到gazebo打开不稳定的问题，导致建图模块无法使用。目前没有发现原因，解决办法是重新运行程序。

**Comment by insunday** [comment]
我可以尝试加一个处理这个问题的excpetion，是要重新运行整个gui还是重新运行建图模块？

**Comment by WendyZheng9953** [comment]
我的解决方法是关闭输入python gui.py的终端，重新运行程序。

**Comment by insunday** [comment]
ok,拿我加了一个异常处理，结束程序并重启python gui，我们可以在建图较长时间没有成功的时候抛这个异常
