### ISSUE TITLE
如何利用激光雷达判断周围障碍物

### ISSUE THREAD

**Issue by insunday** [sebuaa2020/Team101#12]
目前我看到已有的包中只有打开激光雷达的命令，没有通过激光雷达信息给出障碍物距离机器人距离&/位置的包，有人找到这种包了吗？或者需要自己写？

**Comment by WendyZheng9953** [comment]
说到这个问题，目前的自主行走还没有避障功能。

**Comment by WendyZheng9953** [comment]
已经添加了避障功能。对于你提到的问题，是需要监听/scan话题，在go_forward等部分代码有所显示
