### ISSUE TITLE
UI说明的问题

### ISSUE THREAD

**Issue by 17373355** [sebuaa2020/Team101#13]
5.1.3 在本界面中建立好的地图会显示在界面下方图像框内。用户可以同时点击选择起点按钮或选择终点按钮在地图中选择定点巡航的起点与终点（起点默认为机器人当前）
什么是"同时点击选择起点按钮/选择终点按钮“，画面上只有选择终点按钮
![image](https://user-images.githubusercontent.com/47974283/82737275-94fa2a00-9d62-11ea-8166-421ed3f7dd12.png)

**Comment by WendyZheng9953** [comment]
这部分没有和总控类整合完毕
