### ISSUE TITLE
build map & navigation coding

### ISSUE THREAD

**Issue by ANDgate99** [sebuaa2020/Team101#4]

**Comment by ANDgate99** [comment]
单独的功能修改后仿真运行成功，控制类还没完成没有整合

**Comment by WendyZheng9953** [comment]
buildMap已经和总控类进行整合。目前的操作流程是：点击“建图”->点击自主行走操控健->点击“完成建图”。
测试人员须知，自主行走目前只能在建图中使用！并且暂时没有避障功能！
中途遇到gazebo启动问题请看issue 11。
@senbeiasano @pampamda @17373355 @insunday

**Comment by WendyZheng9953** [comment]
测试人员注意，自主行走增加了避障功能！会有提示报错！ @pampamda @senbeiasano @17373355 @insunday

**Comment by WendyZheng9953** [comment]
导航目前实现了到坐标点的避障导航，但由于UI原因还没有与控制类整合。所以现在的版本是调用rviz添加导航。

**Comment by WendyZheng9953** [comment]
修改了导航避障部分的代码，能在导航时距物品有一段距离时进行避障。但由于我的rviz中找不到添加障碍物的选项，只能在gazebo中添加障碍物并观察现象。

**Comment by WendyZheng9953** [comment]
我在自主行走中加入了键盘控制的功能。

**Comment by WendyZheng9953** [comment]
基本代码全部完成，剩余修缮工作由我负责
